"""
Message formatting utilities for trend reports.
"""
from __future__ import annotations

from typing import List, Dict, Any


def format_slack_blocks(trends: List[Dict[str, Any]], top_n: int = 10) -> List[Dict]:
    """
    Format trends as Slack Block Kit blocks.

    Args:
        trends: List of trend dictionaries
        top_n: Number of top trends to include

    Returns:
        List of Slack block dictionaries
    """
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "🔥 Trendwatcher Weekly Report",
                "emoji": True
            }
        },
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"Top {top_n} food trends • Updated {_get_timestamp()}"
                }
            ]
        },
        {"type": "divider"}
    ]

    for i, trend in enumerate(trends[:top_n], start=1):
        # Trend header
        trend_name = trend.get("trend", "Unknown")
        score = trend.get("score", 0)
        countries = ", ".join(trend.get("countries", []))

        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*#{i}. {trend_name}*\n"
                        f"📊 Score: {score} | 🌍 {countries}"
            }
        })

        # Analysis (if available)
        analysis = trend.get("analysis", {})
        if analysis and "product_fit" in analysis:
            product_fit = analysis.get("product_fit", "unknown")
            market_readiness = analysis.get("market_readiness", "unknown")
            timeline = analysis.get("adoption_timeline", "unknown")

            # Emoji indicators
            fit_emoji = {"high": "🟢", "medium": "🟡", "low": "🔴"}.get(product_fit, "⚪")
            market_emoji = {"ready": "✅", "emerging": "🌱", "niche": "🔬"}.get(market_readiness, "❓")

            blocks.append({
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": f"{fit_emoji} Product Fit: *{product_fit}* | "
                                f"{market_emoji} Market: *{market_readiness}* | "
                                f"⏰ Timeline: *{timeline}*"
                    }
                ]
            })

            # Reasoning
            reasoning = analysis.get("product_fit_reasoning", "")
            if reasoning:
                blocks.append({
                    "type": "context",
                    "elements": [
                        {
                            "type": "mrkdwn",
                            "text": f"_{reasoning}_"
                        }
                    ]
                })

        blocks.append({"type": "divider"})

    # Footer
    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": "🤖 Generated by Trendwatcher • <https://github.com/|View on GitHub>"
            }
        ]
    })

    return blocks


def format_email_html(trends: List[Dict[str, Any]], top_n: int = 25) -> str:
    """
    Format trends as HTML email.

    Args:
        trends: List of trend dictionaries
        top_n: Number of top trends to include

    Returns:
        HTML string
    """
    html = """
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f5f5f5;
            }
            .container {
                background-color: white;
                border-radius: 8px;
                padding: 30px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            }
            h1 {
                color: #2c3e50;
                border-bottom: 3px solid #3498db;
                padding-bottom: 10px;
            }
            .timestamp {
                color: #7f8c8d;
                font-size: 14px;
                margin-bottom: 20px;
            }
            table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }
            th {
                background-color: #3498db;
                color: white;
                padding: 12px;
                text-align: left;
                font-weight: 600;
            }
            td {
                padding: 12px;
                border-bottom: 1px solid #ecf0f1;
            }
            tr:hover {
                background-color: #f8f9fa;
            }
            .rank {
                font-weight: bold;
                color: #3498db;
            }
            .score {
                font-weight: 600;
            }
            .badge {
                display: inline-block;
                padding: 3px 8px;
                border-radius: 3px;
                font-size: 12px;
                font-weight: 600;
            }
            .badge-high {
                background-color: #d4edda;
                color: #155724;
            }
            .badge-medium {
                background-color: #fff3cd;
                color: #856404;
            }
            .badge-low {
                background-color: #f8d7da;
                color: #721c24;
            }
            .footer {
                margin-top: 30px;
                padding-top: 20px;
                border-top: 1px solid #ecf0f1;
                color: #7f8c8d;
                font-size: 14px;
                text-align: center;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🔥 Trendwatcher Report</h1>
            <p class="timestamp">""" + f"Top {top_n} food trends • {_get_timestamp()}" + """</p>

            <table>
                <thead>
                    <tr>
                        <th>Rank</th>
                        <th>Trend</th>
                        <th>Score</th>
                        <th>Countries</th>
                        <th>Product Fit</th>
                    </tr>
                </thead>
                <tbody>
    """

    for i, trend in enumerate(trends[:top_n], start=1):
        trend_name = trend.get("trend", "Unknown")
        score = trend.get("score", 0)
        countries = ", ".join(trend.get("countries", []))

        # Analysis badges
        analysis = trend.get("analysis", {})
        product_fit = analysis.get("product_fit", "unknown")
        badge_class = {
            "high": "badge-high",
            "medium": "badge-medium",
            "low": "badge-low"
        }.get(product_fit, "")

        html += f"""
                    <tr>
                        <td class="rank">#{i}</td>
                        <td>{trend_name}</td>
                        <td class="score">{score}</td>
                        <td>{countries}</td>
                        <td><span class="badge {badge_class}">{product_fit}</span></td>
                    </tr>
        """

    html += """
                </tbody>
            </table>

            <div class="footer">
                <p>🤖 Generated by Trendwatcher for Picnic Technologies</p>
            </div>
        </div>
    </body>
    </html>
    """

    return html


def _get_timestamp() -> str:
    """Get current timestamp formatted for display."""
    from datetime import datetime
    return datetime.now().strftime("%Y-%m-%d %H:%M UTC")
